sudo: required

services: 
  - docker 
  
before_intsll:  
  - docker build -t evardanyan/docker-react -f Dockerfile.dev .

script:
  - docker run evardanyan/docker-react  npm start test -- --coverage